### ISSUE TITLE
Rake install throws error on Centos

### ISSUE THREAD

**Issue by vinnytroia** [wpscanteam/CMSScanner#68]
143 files inspected, no offenses detected
/root/.rbenv/versions/2.4.4/bin/ruby -I/root/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rspec-support-3.8.0/lib:/root/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rspec-core-3.8.0/lib /root/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rspec-core-3.8.0/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
...F

Failures:

  1) CMSScanner::Controller::Core#setup_cache when no cache_dir supplied (or default) returns nil
     Failure/Error: if PublicSuffix.valid?(element)

     ArgumentError:
       invalid byte sequence in US-ASCII
     # ./lib/cms_scanner/target/scope.rb:51:in `<<'
     # ./lib/cms_scanner/target.rb:18:in `initialize'
     # ./lib/cms_scanner/controller.rb:31:in `new'
     # ./lib/cms_scanner/controller.rb:31:in `target'
     # ./app/controllers/core.rb:10:in `setup_cache'
     # ./spec/app/controllers/core_spec.rb:33:in `block (4 levels) in <top (required)>'

Finished in 0.02935 seconds (files took 1.08 seconds to load)
4 examples, 1 failure

Failed examples:

rspec ./spec/app/controllers/core_spec.rb:32 # CMSScanner::Controller::Core#setup_cache when no cache_dir supplied (or default) returns nil

Coverage report generated for RSpec to /opt/CMSScanner/coverage. 670 / 1221 LOC (54.87%) covered.
/root/.rbenv/versions/2.4.4/bin/ruby -I/root/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rspec-support-3.8.0/lib:/root/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rspec-core-3.8.0/lib /root/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rspec-core-3.8.0/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed

**Comment by alexsanford** [comment]
It looks like you may be using ruby version 2.4.4. This gem [requires](https://github.com/wpscanteam/CMSScanner/blob/master/cms_scanner.gemspec#L10) `ruby >= 3.0.0`. Can you try on a newer version of ruby and see if that helps?
